## NUMPY


In [1]:
import numpy as np

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
a.ndim

2

In [8]:
a.shape

(2, 7)

In [9]:
a.dtype

dtype('int32')

In [14]:
a.itemsize

4

In [15]:
a.nbytes

56

### modifications in arrays ( elements/rows/columns )

In [17]:
print (a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a[1,4]

12

In [19]:
a[:, 5]


array([ 6, 13])

In [21]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [22]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((4,4),(99))

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [35]:
z= np.zeros([6,6])
print (z)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [34]:
x = np.identity(4)
print (x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
z[1:5, 1:5] = x
print (z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
