In [2]:
import numpy as np
import pandas as pd

1.	Create a NumPy array of shape (3,3) filled with random integers between 1 and 100.

In [10]:
arr1 = np.random.randint (1,100, size = (3,3))
arr1

array([[98, 53, 13],
       [57, 31, 46],
       [33, 70, 50]])

2.	Replace all odd numbers in a NumPy array with -1 without using a loop.

In [13]:
arr2 = np.random.randint (1,100, size = (3,3))
arr2
arr2[arr2 % 2 == 1] = -1
arr2

array([[-1, -1, -1],
       [58, 66, 18],
       [-1, -1, -1]])

3.	Given a NumPy array, find the indices of all elements greater than a given value.

In [15]:
arr3 = np.random.randint (1,100, size = (3,3))
indices = np.where(arr3 >= 50)
indices

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 2, 0, 2]))

4.	Convert a 1D NumPy array into a 2D matrix of shape (n, m).

In [21]:
arr4 = np.array([1,2,3,4,5])
arr5 = arr4.reshape(5,1)
arr5


array([[1],
       [2],
       [3],
       [4],
       [5]])

5.	Compute the sum of all elements in a NumPy array along axis 0 and axis 1.

In [26]:
arr6 = np.random.randint (1,100, size = (3,3))
arr6
xaxis = np.sum(arr6, axis = 0)
yaxis = np.sum(arr6, axis = 1)
print(xaxis)
print(yaxis)
arr6

[167 111 193]
[220 141 110]


array([[58, 83, 79],
       [62, 22, 57],
       [47,  6, 57]])