In [ ]:
import numpy as np
import pandas as pd

1.	Create a NumPy array of shape (3,3) filled with random integers between 1 and 100.

In [ ]:
arr1 = np.random.randint (1,100, size = (3,3))
arr1

array([[98, 53, 13],
       [57, 31, 46],
       [33, 70, 50]])

2.	Replace all odd numbers in a NumPy array with -1 without using a loop.

In [ ]:
arr2 = np.random.randint (1,100, size = (3,3))
arr2
arr2[arr2 % 2 == 1] = -1
arr2

array([[-1, -1, -1],
       [58, 66, 18],
       [-1, -1, -1]])

3.	Given a NumPy array, find the indices of all elements greater than a given value.

In [ ]:
arr3 = np.random.randint (1,100, size = (3,3))
indices = np.where(arr3 >= 50)
indices

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 2, 0, 2]))

4.	Convert a 1D NumPy array into a 2D matrix of shape (n, m).

In [ ]:
arr4 = np.array([1,2,3,4,5])
arr5 = arr4.reshape(5,1)
arr5


array([[1],
       [2],
       [3],
       [4],
       [5]])

5.	Compute the sum of all elements in a NumPy array along axis 0 and axis 1.

In [ ]:
arr6 = np.random.randint (1,100, size = (3,3))
arr6
xaxis = np.sum(arr6, axis = 0)
yaxis = np.sum(arr6, axis = 1)
print(xaxis)
print(yaxis)
arr6

[167 111 193]
[220 141 110]


array([[58, 83, 79],
       [62, 22, 57],
       [47,  6, 57]])

6.	Normalize a NumPy array (scale values to a range between 0 and 1).

In [4]:
import numpy as np
arr7 = np.array([1,2,3,4,5])
arr7 = (arr7 - np.min(arr7)) / (np.max(arr7) - np.min(arr7))
arr7

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

7.	Stack two NumPy arrays vertically and horizontally.

In [5]:
arr8 = np.random.randint(1,100, size = (3,3))
arr9 = np.random.randint(1,100, size = (3,3))
arr8
arr9

print(np.vstack((arr8,arr9)))
print(np.hstack((arr8,arr9)))

[[37 21 30]
 [79 56 54]
 [16 16 28]
 [87 67 72]
 [ 5 70 34]
 [95 97 50]]
[[37 21 30 87 67 72]
 [79 56 54  5 70 34]
 [16 16 28 95 97 50]]


8.	Given a 2D array, swap two rows and swap two columns.

In [7]:
arr10 = np.random.randint(2,20, size = (2,2))
arr10
arr10 = arr10[:,[1,0]]
arr10

array([[ 2, 16],
       [19,  2]])

9.	Find the mean, median, and standard deviation of a NumPy array.

In [8]:
arr11 = np.array([1,2,3,4,5])
print(np.mean(arr11))
print(np.median(arr11))
print(np.std(arr11))

3.0
3.0
1.4142135623730951


10.	Find the unique elements and their counts in a NumPy array.

In [11]:
arr12 = np.array([1,2,2,3,4,555,4,4,4,4,4,5,6,6])
unique = np.unique(arr12)
print(unique)


[  1   2   3   4   5   6 555]


11.	Write a function to find the dot product and cross product of two NumPy arrays.

In [13]:
arr13 = np.array([1,2,3])
arr14 = np.array([1,2,3])

dot = np.dot(arr13,arr14)
cross = np.cross(arr13,arr14)

print ("dot = ",dot)
print ("cross = ",cross)

dot =  14
cross =  [0 0 0]


12.	Given a 3D NumPy array, extract a specific slice from it.

In [15]:
arr15 = np.arange(27).reshape(3, 3, 3)


arr16 = arr15[1, :, :]
print(arr15)
print(arr16)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


13.	Convert a NumPy array of floats into an array of integers without changing the shape.

In [16]:
arr17 = np.array([[1.2, 2.8], [3.5, 4.9]])
arr18 = arr17.astype(int)
print(arr18)

[[1 2]
 [3 4]]


14.	Find the cumulative sum and cumulative product of elements in a NumPy array.

In [22]:
arr19 = np.array([1, 2, 3, 4])

arr20 = np.cumsum(arr19)
arr21 = np.cumprod(arr19)
print(arr20)
print(arr21)

[ 1  3  6 10]
[ 1  2  6 24]


15.	Generate a NumPy array of n linearly spaced numbers between a given range.

In [25]:
arr22 = np.linspace(0, 20, 5)
print(arr22)

[ 0.  5. 10. 15. 20.]


16.	Find the determinant and inverse of a square NumPy matrix.

In [26]:
arr23 = np.array([[1, 2], [3, 4]])

det = np.linalg.det(arr23)
inv = np.linalg.inv(arr23)
print("Determinant:", det)
print("Inverse:\n", inv)

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


17.	Sort a NumPy array along a specific axis.

In [33]:

arr24 = np.random.randint(5, 20, 2)
arr25 = np.sort(arr24, axis=0)
print(arr25)

[ 6 12]


18.	Filter out NaN values from a NumPy array and replace them with a given value.

In [37]:

arr26 = np.array([1, np.nan, 2, np.nan, 3])

arr27 = np.nan_to_num(arr26, nan=2)
arr27

array([1., 2., 2., 2., 3.])

19.	Given a NumPy array, find the indices of the top k largest values

In [38]:
arr28 = np.array([10, 20, 5, 30, 25])
k = 3

arr29 = arr28.argsort()[-k:][::-1]
print(arr29)

[3 4 1]


20.	Perform element-wise addition, subtraction, multiplication, and division on two NumPy arrays of the same shape.

In [40]:
arr30 = np.array([1, 2, 3])
arr31 = np.array([4, 5, 6])

add = arr30 + arr31
sub = arr30 - arr31
mul = arr30 * arr31
div = arr30 / arr31
print("Add:", add)
print("Subtract:", sub)
print("Multiply:", mul)
print("Divide:", div)

Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]
